name = "cafemockup-admin"
main = "admin-worker-final.js"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "cafemockup-db"
database_id = "24562aae-75b9-4705-affd-0b6130e4ffdd"
